--
-- PostgreSQL database dump
--

\restrict bKrlvMSJlINPY14408lqo5KnKQO1W53ChRSHwgRw3qyj2GMbKoi0OwegaDh4wWW

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: business_profiles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.business_profiles (
    profile_id bigint NOT NULL,
    alamat character varying(255),
    biaya_pengantaran_default numeric(15,2),
    created_at timestamp(6) without time zone,
    email character varying(150),
    kota character varying(100) NOT NULL,
    logo_path character varying(255),
    margin_default numeric(5,2),
    mata_uang character varying(10),
    nama_usaha character varying(100) NOT NULL,
    no_whatsapp character varying(20),
    pajak_default numeric(5,2),
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);


ALTER TABLE public.business_profiles OWNER TO postgres;

--
-- Name: business_profiles_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.business_profiles ALTER COLUMN profile_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.business_profiles_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ingredients; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ingredients (
    ingredient_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    harga_per_satuan numeric(15,2) NOT NULL,
    harga_sebelumnya numeric(15,2),
    nama character varying(100) NOT NULL,
    satuan character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);


ALTER TABLE public.ingredients OWNER TO postgres;

--
-- Name: ingredients_ingredient_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ingredients ALTER COLUMN ingredient_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ingredients_ingredient_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: nota_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.nota_items (
    nota_item_id bigint NOT NULL,
    harga_jual_per_porsi numeric(15,2) NOT NULL,
    hpp_per_porsi numeric(15,2) NOT NULL,
    jumlah_porsi integer NOT NULL,
    subtotal numeric(15,2) NOT NULL,
    nota_id bigint NOT NULL,
    recipe_id bigint NOT NULL
);


ALTER TABLE public.nota_items OWNER TO postgres;

--
-- Name: nota_items_nota_item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.nota_items ALTER COLUMN nota_item_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.nota_items_nota_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notas (
    nota_id bigint NOT NULL,
    biaya_pengantaran numeric(15,2),
    created_at timestamp(6) without time zone,
    margin_aktual numeric(5,2),
    nama_acara character varying(100),
    nama_client character varying(100) NOT NULL,
    no_wa_client character varying(20),
    nomor_invoice character varying(20) NOT NULL,
    pajak_persen numeric(5,2),
    status character varying(255) NOT NULL,
    tanggal_acara date,
    total_harga_jual numeric(15,2),
    total_hpp numeric(15,2),
    total_profit numeric(15,2),
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    CONSTRAINT notas_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'SELESAI'::character varying])::text[])))
);


ALTER TABLE public.notas OWNER TO postgres;

--
-- Name: notas_nota_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notas ALTER COLUMN nota_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notas_nota_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.password_reset_tokens (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    expired_at timestamp(6) without time zone NOT NULL,
    is_used boolean NOT NULL,
    token character varying(255) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.password_reset_tokens OWNER TO postgres;

--
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.password_reset_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recipe_ingredients; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.recipe_ingredients (
    recipe_ingredient_id bigint NOT NULL,
    quantity numeric(10,3) NOT NULL,
    ingredient_id bigint NOT NULL,
    recipe_id bigint NOT NULL
);


ALTER TABLE public.recipe_ingredients OWNER TO postgres;

--
-- Name: recipe_ingredients_recipe_ingredient_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.recipe_ingredients ALTER COLUMN recipe_ingredient_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recipe_ingredients_recipe_ingredient_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recipes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.recipes (
    recipe_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    harga_jual numeric(15,2),
    hpp_final numeric(15,2),
    hpp_manual numeric(15,2),
    jumlah_porsi integer NOT NULL,
    margin numeric(5,2) NOT NULL,
    nama_resep character varying(100) NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);


ALTER TABLE public.recipes OWNER TO postgres;

--
-- Name: recipes_recipe_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.recipes ALTER COLUMN recipe_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recipes_recipe_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.refresh_tokens (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    expired_at timestamp(6) without time zone NOT NULL,
    token character varying(255) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.refresh_tokens OWNER TO postgres;

--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shopping_list_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shopping_list_items (
    shopping_list_item_id bigint NOT NULL,
    is_bought boolean NOT NULL,
    satuan character varying(20) NOT NULL,
    total_harga numeric(15,2) NOT NULL,
    total_quantity numeric(10,3) NOT NULL,
    ingredient_id bigint NOT NULL,
    shopping_list_id bigint NOT NULL
);


ALTER TABLE public.shopping_list_items OWNER TO postgres;

--
-- Name: shopping_list_items_shopping_list_item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.shopping_list_items ALTER COLUMN shopping_list_item_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shopping_list_items_shopping_list_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shopping_list_recipes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shopping_list_recipes (
    id bigint NOT NULL,
    recipe_id bigint NOT NULL,
    shopping_list_id bigint NOT NULL
);


ALTER TABLE public.shopping_list_recipes OWNER TO postgres;

--
-- Name: shopping_list_recipes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.shopping_list_recipes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shopping_list_recipes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shopping_lists; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shopping_lists (
    shopping_list_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);


ALTER TABLE public.shopping_lists OWNER TO postgres;

--
-- Name: shopping_lists_shopping_list_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.shopping_lists ALTER COLUMN shopping_list_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shopping_lists_shopping_list_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: subscriptions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.subscriptions (
    subscription_id bigint NOT NULL,
    amount numeric(15,2) NOT NULL,
    created_at timestamp(6) without time zone,
    end_date date,
    midtrans_order_id character varying(100) NOT NULL,
    midtrans_transaction_id character varying(100),
    start_date date,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    CONSTRAINT subscriptions_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying, 'EXPIRED'::character varying])::text[])))
);


ALTER TABLE public.subscriptions OWNER TO postgres;

--
-- Name: subscriptions_subscription_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.subscriptions ALTER COLUMN subscription_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscriptions_subscription_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(150) NOT NULL,
    google_id character varying(255),
    is_premium boolean NOT NULL,
    nama_pemilik character varying(100) NOT NULL,
    password character varying(255),
    updated_at timestamp(6) without time zone
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: business_profiles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.business_profiles (profile_id, alamat, biaya_pengantaran_default, created_at, email, kota, logo_path, margin_default, mata_uang, nama_usaha, no_whatsapp, pajak_default, updated_at, user_id) FROM stdin;
\.


--
-- Data for Name: ingredients; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ingredients (ingredient_id, created_at, harga_per_satuan, harga_sebelumnya, nama, satuan, updated_at, user_id) FROM stdin;
\.


--
-- Data for Name: nota_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.nota_items (nota_item_id, harga_jual_per_porsi, hpp_per_porsi, jumlah_porsi, subtotal, nota_id, recipe_id) FROM stdin;
\.


--
-- Data for Name: notas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notas (nota_id, biaya_pengantaran, created_at, margin_aktual, nama_acara, nama_client, no_wa_client, nomor_invoice, pajak_persen, status, tanggal_acara, total_harga_jual, total_hpp, total_profit, updated_at, user_id) FROM stdin;
\.


--
-- Data for Name: password_reset_tokens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.password_reset_tokens (id, created_at, expired_at, is_used, token, user_id) FROM stdin;
2	2026-05-14 17:41:26.389562	2026-05-14 18:41:26.388564	t	15b794a9-d44a-456f-a841-bcd7f581667f	1
\.


--
-- Data for Name: recipe_ingredients; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.recipe_ingredients (recipe_ingredient_id, quantity, ingredient_id, recipe_id) FROM stdin;
\.


--
-- Data for Name: recipes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.recipes (recipe_id, created_at, harga_jual, hpp_final, hpp_manual, jumlah_porsi, margin, nama_resep, updated_at, user_id) FROM stdin;
\.


--
-- Data for Name: refresh_tokens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.refresh_tokens (id, created_at, expired_at, token, user_id) FROM stdin;
8	2026-05-14 17:42:16.586305	2026-05-21 17:42:16.586306	86f24c7e-0a89-4247-b903-14c4bcbefe60	1
9	2026-05-14 17:44:14.983332	2026-05-21 17:44:14.979359	4997e3fb-dd64-44e4-b70a-634595670df9	2
\.


--
-- Data for Name: shopping_list_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.shopping_list_items (shopping_list_item_id, is_bought, satuan, total_harga, total_quantity, ingredient_id, shopping_list_id) FROM stdin;
\.


--
-- Data for Name: shopping_list_recipes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.shopping_list_recipes (id, recipe_id, shopping_list_id) FROM stdin;
\.


--
-- Data for Name: shopping_lists; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.shopping_lists (shopping_list_id, created_at, user_id) FROM stdin;
\.


--
-- Data for Name: subscriptions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.subscriptions (subscription_id, amount, created_at, end_date, midtrans_order_id, midtrans_transaction_id, start_date, status, updated_at, user_id) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (user_id, created_at, email, google_id, is_premium, nama_pemilik, password, updated_at) FROM stdin;
1	2026-05-14 16:34:03.854969	hanifafghani92@gmail.com	\N	f	Hanif	$2a$12$R1f.bHu7ZFGPci2mjPLDr.KSXvFHHXNB5biDfw6ZKCwYQ9gNlQixC	2026-05-14 17:42:07.168836
2	2026-05-14 17:44:14.971319	jeanjen10111@gmail.com	118110701206150361926	f	Jenjen	\N	2026-05-14 17:44:14.971319
\.


--
-- Name: business_profiles_profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.business_profiles_profile_id_seq', 1, false);


--
-- Name: ingredients_ingredient_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ingredients_ingredient_id_seq', 1, false);


--
-- Name: nota_items_nota_item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.nota_items_nota_item_id_seq', 1, false);


--
-- Name: notas_nota_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notas_nota_id_seq', 1, false);


--
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.password_reset_tokens_id_seq', 2, true);


--
-- Name: recipe_ingredients_recipe_ingredient_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.recipe_ingredients_recipe_ingredient_id_seq', 1, false);


--
-- Name: recipes_recipe_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.recipes_recipe_id_seq', 1, false);


--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.refresh_tokens_id_seq', 9, true);


--
-- Name: shopping_list_items_shopping_list_item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.shopping_list_items_shopping_list_item_id_seq', 1, false);


--
-- Name: shopping_list_recipes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.shopping_list_recipes_id_seq', 1, false);


--
-- Name: shopping_lists_shopping_list_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.shopping_lists_shopping_list_id_seq', 1, false);


--
-- Name: subscriptions_subscription_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.subscriptions_subscription_id_seq', 1, false);


--
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_user_id_seq', 2, true);


--
-- Name: business_profiles business_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.business_profiles
    ADD CONSTRAINT business_profiles_pkey PRIMARY KEY (profile_id);


--
-- Name: ingredients ingredients_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ingredients
    ADD CONSTRAINT ingredients_pkey PRIMARY KEY (ingredient_id);


--
-- Name: nota_items nota_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nota_items
    ADD CONSTRAINT nota_items_pkey PRIMARY KEY (nota_item_id);


--
-- Name: notas notas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notas
    ADD CONSTRAINT notas_pkey PRIMARY KEY (nota_id);


--
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);


--
-- Name: recipe_ingredients recipe_ingredients_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recipe_ingredients
    ADD CONSTRAINT recipe_ingredients_pkey PRIMARY KEY (recipe_ingredient_id);


--
-- Name: recipes recipes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recipes
    ADD CONSTRAINT recipes_pkey PRIMARY KEY (recipe_id);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: shopping_list_items shopping_list_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shopping_list_items
    ADD CONSTRAINT shopping_list_items_pkey PRIMARY KEY (shopping_list_item_id);


--
-- Name: shopping_list_recipes shopping_list_recipes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shopping_list_recipes
    ADD CONSTRAINT shopping_list_recipes_pkey PRIMARY KEY (id);


--
-- Name: shopping_lists shopping_lists_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shopping_lists
    ADD CONSTRAINT shopping_lists_pkey PRIMARY KEY (shopping_list_id);


--
-- Name: subscriptions subscriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscriptions_pkey PRIMARY KEY (subscription_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: password_reset_tokens uk71lqwbwtklmljk3qlsugr1mig; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT uk71lqwbwtklmljk3qlsugr1mig UNIQUE (token);


--
-- Name: business_profiles ukfbfb8fvcm18wgvn1g4vtygy0n; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.business_profiles
    ADD CONSTRAINT ukfbfb8fvcm18wgvn1g4vtygy0n UNIQUE (user_id);


--
-- Name: refresh_tokens ukghpmfn23vmxfu3spu3lfg4r2d; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT ukghpmfn23vmxfu3spu3lfg4r2d UNIQUE (token);


--
-- Name: notas ukmuqkg1jloi2mjgw5iokeixg8b; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notas
    ADD CONSTRAINT ukmuqkg1jloi2mjgw5iokeixg8b UNIQUE (nomor_invoice);


--
-- Name: users ukovh8xmu9ac27t18m56gri58i1; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukovh8xmu9ac27t18m56gri58i1 UNIQUE (google_id);


--
-- Name: subscriptions ukqvxa361kp2jpuod0fyjpa558v; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT ukqvxa361kp2jpuod0fyjpa558v UNIQUE (midtrans_order_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: refresh_tokens fk1lih5y2npsf8u5o3vhdb9y0os; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk1lih5y2npsf8u5o3vhdb9y0os FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: ingredients fk3c7wmxbd9aqoh9hluau9wvwy1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ingredients
    ADD CONSTRAINT fk3c7wmxbd9aqoh9hluau9wvwy1 FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: business_profiles fk6rtkyif43obkivqccykb4id3p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.business_profiles
    ADD CONSTRAINT fk6rtkyif43obkivqccykb4id3p FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: recipe_ingredients fkcqlw8sor5ut10xsuj3jnttkc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recipe_ingredients
    ADD CONSTRAINT fkcqlw8sor5ut10xsuj3jnttkc FOREIGN KEY (recipe_id) REFERENCES public.recipes(recipe_id);


--
-- Name: shopping_list_recipes fkcyg3gjrkvryny00ajeel5o9xr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shopping_list_recipes
    ADD CONSTRAINT fkcyg3gjrkvryny00ajeel5o9xr FOREIGN KEY (recipe_id) REFERENCES public.recipes(recipe_id);


--
-- Name: notas fke6dth4tmqs2tarcl3ppuuyf4a; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notas
    ADD CONSTRAINT fke6dth4tmqs2tarcl3ppuuyf4a FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: recipe_ingredients fkgukrw6na9f61kb8djkkuvyxy8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recipe_ingredients
    ADD CONSTRAINT fkgukrw6na9f61kb8djkkuvyxy8 FOREIGN KEY (ingredient_id) REFERENCES public.ingredients(ingredient_id);


--
-- Name: subscriptions fkhro52ohfqfbay9774bev0qinr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT fkhro52ohfqfbay9774bev0qinr FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: shopping_list_recipes fkhrvq3r13o2fbev5d7r9gpno8g; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shopping_list_recipes
    ADD CONSTRAINT fkhrvq3r13o2fbev5d7r9gpno8g FOREIGN KEY (shopping_list_id) REFERENCES public.shopping_lists(shopping_list_id);


--
-- Name: password_reset_tokens fkk3ndxg5xp6v7wd4gjyusp15gq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT fkk3ndxg5xp6v7wd4gjyusp15gq FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: recipes fklc3x6yty3xsupx80hqbj9ayos; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recipes
    ADD CONSTRAINT fklc3x6yty3xsupx80hqbj9ayos FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: shopping_lists fkllqvt8eyww5jxnjjun6upx184; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shopping_lists
    ADD CONSTRAINT fkllqvt8eyww5jxnjjun6upx184 FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: shopping_list_items fkm9sy7hbp3ur1y0g8qog1o7621; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shopping_list_items
    ADD CONSTRAINT fkm9sy7hbp3ur1y0g8qog1o7621 FOREIGN KEY (shopping_list_id) REFERENCES public.shopping_lists(shopping_list_id);


--
-- Name: nota_items fkqk3pcbewbirwg2f6xaqayw0ru; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nota_items
    ADD CONSTRAINT fkqk3pcbewbirwg2f6xaqayw0ru FOREIGN KEY (nota_id) REFERENCES public.notas(nota_id);


--
-- Name: shopping_list_items fkripfshrqprgo8kk87idintitg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shopping_list_items
    ADD CONSTRAINT fkripfshrqprgo8kk87idintitg FOREIGN KEY (ingredient_id) REFERENCES public.ingredients(ingredient_id);


--
-- Name: nota_items fkrty14uj5cb5539umip7godjhs; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nota_items
    ADD CONSTRAINT fkrty14uj5cb5539umip7godjhs FOREIGN KEY (recipe_id) REFERENCES public.recipes(recipe_id);


--
-- PostgreSQL database dump complete
--

\unrestrict bKrlvMSJlINPY14408lqo5KnKQO1W53ChRSHwgRw3qyj2GMbKoi0OwegaDh4wWW

