services:
  app:
    image: ${DOCKER_USERNAME}/katerly-backend:latest
    container_name: katerly-backend
    restart: unless-stopped
    network_mode: host
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    volumes:
      - uploads_data:/app/uploads

volumes:
  uploads_data: